apiVersion: v1
kind: Pod
metadata:
  labels:
    role: nfs-server
  name: nfs-server
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/volume/nfs:1.0
    imagePullPolicy: IfNotPresent
    name: nfs-server
    ports:
    - containerPort: 2049
      name: nfs-0
      protocol: TCP
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /exports
      name: path0
  restartPolicy: Always
  volumes:
  - emptyDir: {}
    name: path0
